#!/bin/bash

#
#  Copyright (C) 2018-2023 by Lars Wienbrandt,
#  Institute of Clinical Molecular Biology, Kiel University
#
#  This file is part of Checkphase.
#
#  Checkphase is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Checkphase is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Checkphase. If not, see <https://www.gnu.org/licenses/>.
#

# extracts information from checkphase reports to tab-separated output (tsv))
if [[ $# == 0 ]]; then
  echo "Usage: checkphase_extract <list of checkphase ouput files>"
  echo "Reads checkphase information from provided files and generates a .tsv with the most important information."
  exit 1
fi

# create a '\t' separated list from the command line arguments
sep='\\t'
FILES=$(printf "%s$sep" "$@")
FILES="${FILES%$sep}" # remove trailing separator

gawk 'BEGIN {
 files="\t'$FILES'"
 Nquery="Query samples"
 Mcheck="Checked variants"
 Mcheck_maf01="Checked MAF>=0.1"
 Mcheck_maf001="Checked MAF>=0.01"
 Mcheck_maf0001="Checked MAF>=0.001"
 Mcheck_maf00001="Checked MAF>=0.0001"
 Mtyped="Checked typed variants"

 Totgterr="Total genotype errors"
 Totgterr_maf01="Total genotype errors (MAF>=0.1)"
 Totgterr_maf001="Total genotype errors (MAF>=0.01)"
 Totgterr_maf0001="Total genotype errors (MAF>=0.001)"
 Totgterr_maf00001="Total genotype errors (MAF>=0.0001)"
 Avgterr="Average gt error rate"
 Avgterr_maf01="Average gt error rate (MAF>=0.1)"
 Avgterr_maf001="Average gt error rate (MAF>=0.01)"
 Avgterr_maf0001="Average gt error rate (MAF>=0.001)"
 Avgterr_maf00001="Average gt error rate (MAF>=0.0001)"
 Avgterr2="Mean squared error"
 Avgterr2_maf01="Mean squared error (MAF>=0.1)"
 Avgterr2_maf001="Mean squared error (MAF>=0.01)"
 Avgterr2_maf0001="Mean squared error (MAF>=0.001)"
 Avgterr2_maf00001="Mean squared error (MAF>=0.0001)"
 Corr2_compl="correlation r2 (complete)"
 Corr2_compl_maf01="correlation r2 (complete, MAF>=0.1)"
 Corr2_compl_maf001="correlation r2 (complete, MAF>=0.01)"
 Corr2_compl_maf0001="correlation r2 (complete, MAF>=0.001)"
 Corr2_compl_maf00001="correlation r2 (complete, MAF>=0.0001)"
 Corr2_varav="correlation r2 (var av.)"
 Corr2_varav_maf01="correlation r2 (var av., MAF>=0.1)"
 Corr2_varav_maf001="correlation r2 (var av., MAF>=0.01)"
 Corr2_varav_maf0001="correlation r2 (var av., MAF>=0.001)"
 Corr2_varav_maf00001="correlation r2 (var av., MAF>=0.0001)"

 Totgterr_soft="Total genotype errors (soft)"
 Totgterr_soft_maf01="Total genotype errors (MAF>=0.1) (soft)"
 Totgterr_soft_maf001="Total genotype errors (MAF>=0.01) (soft)"
 Totgterr_soft_maf0001="Total genotype errors (MAF>=0.001) (soft)"
 Totgterr_soft_maf00001="Total genotype errors (MAF>=0.0001) (soft)"
 Avgterr_soft="Average gt error rate (soft)"
 Avgterr_soft_maf01="Average gt error rate (MAF>=0.1) (soft)"
 Avgterr_soft_maf001="Average gt error rate (MAF>=0.01) (soft)"
 Avgterr_soft_maf0001="Average gt error rate (MAF>=0.001) (soft)"
 Avgterr_soft_maf00001="Average gt error rate (MAF>=0.0001) (soft)"
 Avgterr2_soft="Mean squared error (soft)"
 Avgterr2_soft_maf01="Mean squared error (MAF>=0.1) (soft)"
 Avgterr2_soft_maf001="Mean squared error (MAF>=0.01) (soft)"
 Avgterr2_soft_maf0001="Mean squared error (MAF>=0.001) (soft)"
 Avgterr2_soft_maf00001="Mean squared error (MAF>=0.0001) (soft)"
 Corr2_compl_soft="correlation r2 (complete) (soft)"
 Corr2_compl_soft_maf01="correlation r2 (complete, MAF>=0.1) (soft)"
 Corr2_compl_soft_maf001="correlation r2 (complete, MAF>=0.01) (soft)"
 Corr2_compl_soft_maf0001="correlation r2 (complete, MAF>=0.001) (soft)"
 Corr2_compl_soft_maf00001="correlation r2 (complete, MAF>=0.0001) (soft)"
 Corr2_varav_soft="correlation r2 (var av.) (soft)"
 Corr2_varav_soft_maf01="correlation r2 (var av., MAF>=0.1) (soft)"
 Corr2_varav_soft_maf001="correlation r2 (var av., MAF>=0.01) (soft)"
 Corr2_varav_soft_maf0001="correlation r2 (var av., MAF>=0.001) (soft)"
 Corr2_varav_soft_maf00001="correlation r2 (var av., MAF>=0.0001) (soft)"

 Totswerr="Total switch errors"
 Avswerr="Average sw error rate"
 Totswerr_typed="Total switch errors (typed)"
 Avswerr_typed="Average sw error rate (typed)"
}

# number of query samples and checked variants
/Query samples:/{Nquery=(Nquery "\t" $5); next}
/Checked variants:/{Mcheck=(Mcheck "\t" $3); next}
/Checked MAF>=0.1:/{Mcheck_maf01=(Mcheck_maf01 "\t" $3); next}
/Checked MAF>=0.01:/{Mcheck_maf001=(Mcheck_maf001 "\t" $3); next}
/Checked MAF>=0.001:/{Mcheck_maf0001=(Mcheck_maf0001 "\t" $3); next}
/Checked MAF>=0.0001:/{Mcheck_maf00001=(Mcheck_maf00001 "\t" $3); next}
/Checked typed variants:/{Mtyped=(Mtyped "\t" $4); next}

# errors
/Total genotype errors:/{Totgterr=(Totgterr "\t" $4); next}
/Total genotype errors \(MAF>=0.1\):/{Totgterr_maf01=(Totgterr_maf01 "\t" $5); next}
/Total genotype errors \(MAF>=0.01\):/{Totgterr_maf001=(Totgterr_maf001 "\t" $5); next}
/Total genotype errors \(MAF>=0.001\):/{Totgterr_maf0001=(Totgterr_maf0001 "\t" $5); next}
/Total genotype errors \(MAF>=0.0001\):/{Totgterr_maf00001=(Totgterr_maf00001 "\t" $5); next}
/Total genotype errors \(soft\):/{Totgterr_soft=(Totgterr_soft "\t" $5); next}
/Total genotype errors \(MAF>=0.1\) \(soft\):/{Totgterr_soft_maf01=(Totgterr_soft_maf01 "\t" $6); next}
/Total genotype errors \(MAF>=0.01\) \(soft\):/{Totgterr_soft_maf001=(Totgterr_soft_maf001 "\t" $6); next}
/Total genotype errors \(MAF>=0.001\) \(soft\):/{Totgterr_soft_maf0001=(Totgterr_soft_maf0001 "\t" $6); next}
/Total genotype errors \(MAF>=0.0001\) \(soft\):/{Totgterr_soft_maf00001=(Totgterr_soft_maf00001 "\t" $6); next}
/Total switch errors:/{Totswerr=(Totswerr "\t" $4); next}
/Total switch errors \(typed\):/{Totswerr_typed=(Totswerr_typed "\t" $5); next}

# error rates
/Average gt error rate:/{Avgterr=(Avgterr "\t" $5); next}
/Average gt error rate \(MAF>=0.1\):/{Avgterr_maf01=(Avgterr_maf01 "\t" $6); next}
/Average gt error rate \(MAF>=0.01\):/{Avgterr_maf001=(Avgterr_maf001 "\t" $6); next}
/Average gt error rate \(MAF>=0.001\):/{Avgterr_maf0001=(Avgterr_maf0001 "\t" $6); next}
/Average gt error rate \(MAF>=0.0001\):/{Avgterr_maf00001=(Avgterr_maf00001 "\t" $6); next}
/Mean squared error:/{Avgterr2=(Avgterr2 "\t" $4); next}
/Mean squared error \(MAF>=0.1\):/{Avgterr2_maf01=(Avgterr2_maf01 "\t" $5); next}
/Mean squared error \(MAF>=0.01\):/{Avgterr2_maf001=(Avgterr2_maf001 "\t" $5); next}
/Mean squared error \(MAF>=0.001\):/{Avgterr2_maf0001=(Avgterr2_maf0001 "\t" $5); next}
/Mean squared error \(MAF>=0.0001\):/{Avgterr2_maf00001=(Avgterr2_maf00001 "\t" $5); next}
/Average gt error rate \(soft\):/{Avgterr_soft=(Avgterr_soft "\t" $6); next}
/Average gt error rate \(MAF>=0.1\) \(soft\):/{Avgterr_soft_maf01=(Avgterr_soft_maf01 "\t" $7); next}
/Average gt error rate \(MAF>=0.01\) \(soft\):/{Avgterr_soft_maf001=(Avgterr_soft_maf001 "\t" $7); next}
/Average gt error rate \(MAF>=0.001\) \(soft\):/{Avgterr_soft_maf0001=(Avgterr_soft_maf0001 "\t" $7); next}
/Average gt error rate \(MAF>=0.0001\) \(soft\):/{Avgterr_soft_maf00001=(Avgterr_soft_maf00001 "\t" $7); next}
/Mean squared error \(soft\):/{Avgterr2_soft=(Avgterr2_soft "\t" $5); next}
/Mean squared error \(MAF>=0.1\) \(soft\):/{Avgterr2_soft_maf01=(Avgterr2_soft_maf01 "\t" $6); next}
/Mean squared error \(MAF>=0.01\) \(soft\):/{Avgterr2_soft_maf001=(Avgterr2_soft_maf001 "\t" $6); next}
/Mean squared error \(MAF>=0.001\) \(soft\):/{Avgterr2_soft_maf0001=(Avgterr2_soft_maf0001 "\t" $6); next}
/Mean squared error \(MAF>=0.0001\) \(soft\):/{Avgterr2_soft_maf00001=(Avgterr2_soft_maf00001 "\t" $6); next}
/Average sw error rate:/{Avswerr=(Avswerr "\t" $5); next}
/Average sw error rate \(typed\):/{Avswerr_typed=(Avswerr_typed "\t" $6); next}

# r2
/correlation r2 \(complete\):/{Corr2_compl=(Corr2_compl "\t" $4); next}
/correlation r2 \(complete, MAF>=0.1\):/{Corr2_compl_maf01=(Corr2_compl_maf01 "\t" $5); next}
/correlation r2 \(complete, MAF>=0.01\):/{Corr2_compl_maf001=(Corr2_compl_maf001 "\t" $5); next}
/correlation r2 \(complete, MAF>=0.001\):/{Corr2_compl_maf0001=(Corr2_compl_maf0001 "\t" $5); next}
/correlation r2 \(complete, MAF>=0.0001\):/{Corr2_compl_maf00001=(Corr2_compl_maf00001 "\t" $5); next}
/correlation r2 \(var av.\):/{Corr2_varav=(Corr2_varav "\t" $5); next}
/correlation r2 \(var av., MAF>=0.1\):/{Corr2_varav_maf01=(Corr2_varav_maf01 "\t" $6); next}
/correlation r2 \(var av., MAF>=0.01\):/{Corr2_varav_maf001=(Corr2_varav_maf001 "\t" $6); next}
/correlation r2 \(var av., MAF>=0.001\):/{Corr2_varav_maf0001=(Corr2_varav_maf0001 "\t" $6); next}
/correlation r2 \(var av., MAF>=0.0001\):/{Corr2_varav_maf00001=(Corr2_varav_maf00001 "\t" $6); next}
/correlation r2 \(complete\) \(soft\):/{Corr2_compl_soft=(Corr2_compl_soft "\t" $5); next}
/correlation r2 \(complete, MAF>=0.1\) \(soft\):/{Corr2_compl_soft_maf01=(Corr2_compl_soft_maf01 "\t" $6); next}
/correlation r2 \(complete, MAF>=0.01\) \(soft\):/{Corr2_compl_soft_maf001=(Corr2_compl_soft_maf001 "\t" $6); next}
/correlation r2 \(complete, MAF>=0.001\) \(soft\):/{Corr2_compl_soft_maf0001=(Corr2_compl_soft_maf0001 "\t" $6); next}
/correlation r2 \(complete, MAF>=0.0001\) \(soft\):/{Corr2_compl_soft_maf00001=(Corr2_compl_soft_maf00001 "\t" $6); next}
/correlation r2 \(var av.\) \(soft\):/{Corr2_varav_soft=(Corr2_varav_soft "\t" $6); next}
/correlation r2 \(var av., MAF>=0.1\) \(soft\):/{Corr2_varav_soft_maf01=(Corr2_varav_soft_maf01 "\t" $7); next}
/correlation r2 \(var av., MAF>=0.01\) \(soft\):/{Corr2_varav_soft_maf001=(Corr2_varav_soft_maf001 "\t" $7); next}
/correlation r2 \(var av., MAF>=0.001\) \(soft\):/{Corr2_varav_soft_maf0001=(Corr2_varav_soft_maf0001 "\t" $7); next}
/correlation r2 \(var av., MAF>=0.0001\) \(soft\):/{Corr2_varav_soft_maf00001=(Corr2_varav_soft_maf00001 "\t" $7); next}

# print TSV output
END {
print files
print Nquery
print Mcheck
print Mcheck_maf01
print Mcheck_maf001
print Mcheck_maf0001
print Mcheck_maf00001
print Mtyped

print Totgterr
print Totgterr_maf01
print Totgterr_maf001
print Totgterr_maf0001
print Totgterr_maf00001
print Avgterr
print Avgterr_maf01
print Avgterr_maf001
print Avgterr_maf0001
print Avgterr_maf00001
print Avgterr2
print Avgterr2_maf01
print Avgterr2_maf001
print Avgterr2_maf0001
print Avgterr2_maf00001
print Corr2_compl
print Corr2_compl_maf01
print Corr2_compl_maf001
print Corr2_compl_maf0001
print Corr2_compl_maf00001
print Corr2_varav
print Corr2_varav_maf01
print Corr2_varav_maf001
print Corr2_varav_maf0001
print Corr2_varav_maf00001

print Totgterr_soft
print Totgterr_soft_maf01
print Totgterr_soft_maf001
print Totgterr_soft_maf0001
print Totgterr_soft_maf00001
print Avgterr_soft
print Avgterr_soft_maf01
print Avgterr_soft_maf001
print Avgterr_soft_maf0001
print Avgterr_soft_maf00001
print Avgterr2_soft
print Avgterr2_soft_maf01
print Avgterr2_soft_maf001
print Avgterr2_soft_maf0001
print Avgterr2_soft_maf00001
print Corr2_compl_soft
print Corr2_compl_soft_maf01
print Corr2_compl_soft_maf001
print Corr2_compl_soft_maf0001
print Corr2_compl_soft_maf00001
print Corr2_varav_soft
print Corr2_varav_soft_maf01
print Corr2_varav_soft_maf001
print Corr2_varav_soft_maf0001
print Corr2_varav_soft_maf00001

print Totswerr
print Avswerr
print Totswerr_typed
print Avswerr_typed
}' $@
